# Code GPS v3.1-final | 19 LiveViews | 28 Components

# === ROUTES ===
/: AshfolioWeb.DashboardLive ❌
/accounts: AshfolioWeb.AccountLive ❌
/accounts/:id: AshfolioWeb.AccountLive ❌
/accounts/:id/edit: AshfolioWeb.AccountLive ❌
/accounts/new: AshfolioWeb.AccountLive ❌
/advanced_analytics: AshfolioWeb.AdvancedAnalyticsLive ❌
/categories: AshfolioWeb.CategoryLive ❌
/categories/:id/edit: AshfolioWeb.CategoryLive ❌
/categories/new: AshfolioWeb.CategoryLive ❌
/corporate-actions: AshfolioWeb.CorporateActionLive ❌
/corporate-actions/:id/edit: AshfolioWeb.CorporateActionLive ❌
/corporate-actions/new: AshfolioWeb.CorporateActionLive ❌
/expenses: AshfolioWeb.ExpenseLive ❌
/expenses/:id/edit: AshfolioWeb.ExpenseLive ❌
/expenses/analytics: AshfolioWeb.ExpenseLive ❌
/expenses/import: AshfolioWeb.ExpenseLive ❌
/expenses/new: AshfolioWeb.ExpenseLive ❌
/forecast: AshfolioWeb.ForecastLive ❌
/goals: AshfolioWeb.FinancialGoalLive ❌
/goals/:id/edit: AshfolioWeb.FinancialGoalLive ❌
/goals/new: AshfolioWeb.FinancialGoalLive ❌
/money-ratios: AshfolioWeb.MoneyRatiosLive ❌
/net_worth: AshfolioWeb.NetWorthLive ❌
/retirement: AshfolioWeb.RetirementLive ❌
/tax-planning: AshfolioWeb.TaxPlanningLive ❌
/transactions: AshfolioWeb.TransactionLive ❌

# === LIVE VIEWS ===
Index:
  file: lib/ashfolio_web/live/account_live/index.ex
  mount: 13 | render: 183
  events: ["new_account", "filter_accounts", "edit_account", "delete_account", "toggle_exclusion"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Show:
  file: lib/ashfolio_web/live/account_live/show.ex
  mount: 10 | render: 36
  events: ["show_balance_update_modal"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/advanced_analytics_live/index.ex
  mount: 25 | render: 
  events: ["calculate_twr", "calculate_mwr", "calculate_rolling_returns", "calculate_risk_metrics", "refresh_all", "clear_cache", "show_cache_stats"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/benchmark_live/index.ex
  mount: 17 | render: 40
  events: ["update_form", "use_current_portfolio", "run_analysis"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/category_live/index.ex
  mount: 11 | render: 134
  events: ["new_category", "filter_categories", "edit_category", "delete_category", "cancel_form"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/corporate_action_live/index.ex
  mount: 11 | render: 
  events: ["filter", "apply_action", "preview_action", "reverse_action", "delete"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Dashboard:
  file: lib/ashfolio_web/live/dashboard_live.ex
  mount: 20 | render: 158
  events: ["refresh_prices", "sort", "create_snapshot"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Example:
  file: lib/ashfolio_web/live/example_live.ex
  mount: 14 | render: 42
  events: ["simulate_error", "simulate_success", "clear_flash"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Analytics:
  file: lib/ashfolio_web/live/expense_live/analytics.ex
  mount: 13 | render: 119
  events: ["change_date_range", "update_year_comparison", "apply_advanced_filters", "apply_date_range"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Import:
  file: lib/ashfolio_web/live/expense_live/import.ex
  mount: 12 | render: 93
  events: ["validate", "select_import_type", "upload", "validate_import", "import"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/expense_live/index.ex
  mount: 12 | render: 105
  events: ["sort", "search", "toggle_filters", "filter", "clear_filters"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/financial_goal_live/index.ex
  mount: 12 | render: 130
  events: ["sort", "toggle_filters", "filter", "clear_filters", "delete_goal", "setup_emergency_fund"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Forecast:
  file: lib/ashfolio_web/live/financial_planning_live/forecast.ex
  mount: 13 | render: 176
  events: ["calculate_forecast", "switch_scenario", "toggle_advanced_settings", "analyze_contribution", "optimize_for_goal", "clear_results", "export_forecast"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/forecast_live.ex
  mount: 22 | render: 268
  events: ["update_form", "calculate_projection", "calculate_scenarios", "analyze_contributions", "switch_tab"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/money_ratios_live/index.ex
  mount: 23 | render: 
  events: ["switch_tab", "save_profile"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/net_worth_live/index.ex
  mount: 13 | render: 73
  events: ["change_date_range", "create_snapshot"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/retirement_live/index.ex
  mount: 20 | render: 
  events: ["calculate", "use_historical_expenses"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/tax_planning_live/index.ex
  mount: 15 | render: 42
  events: ["switch_tab", "update_tax_year", "update_account", "update_tax_rate", "refresh_analysis"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3
Index:
  file: lib/ashfolio_web/live/transaction_live/index.ex
  mount: 19 | render: 558
  events: ["new_transaction", "edit_transaction", "filter_transactions", "filter_by_category", "apply_composite_filters", "clear_filters", "delete_transaction"]
  subscriptions: []
  missing: ["accounts", "transactions", "net_worth", "expenses"]|...3

# === KEY COMPONENTS ===
flash: lib/ashfolio_web/components/core_components.ex:111 (112x)
icon: lib/ashfolio_web/components/core_components.ex:599 (109x)
list: lib/ashfolio_web/components/core_components.ex:541 (106x)
input: lib/ashfolio_web/components/core_components.ex:295 (96x)
input: lib/ashfolio_web/components/core_components.ex:306 (96x)
input: lib/ashfolio_web/components/core_components.ex:332 (96x)

# === DEPENDENCIES ===
bandit: ❌ (0)
credo: ❌ (0)
dns_cluster: ❌ (0)
ecto_sql: ❌ (0)
ecto_sqlite3: ❌ (0)
esbuild: ❌ (0)
finch: ❌ (0)
floki: ❌ (0)
gettext: ❌ (7)
heroicons: ❌ (0)
jason: ❌ (0)
lazy_html: ❌ (0)
phoenix: ❌ (27)
phoenix_ecto: ❌ (0)
phoenix_html: ❌ (0)
phoenix_live_dashboard: ❌ (0)
phoenix_live_reload: ❌ (0)
phoenix_live_view: ❌ (0)
swoosh: ❌ (1)
tailwind: ❌ (1)
telemetry_metrics: ❌ (0)
telemetry_poller: ❌ (0)

# === FRESHNESS ===
recent: ["lib/ashfolio/portfolio/optimization/portfolio_optimizer.ex", "lib/ashfolio/portfolio/optimization/two_asset_optimizer.ex", "lib/ashfolio/portfolio/calculators/correlation_calculator.ex", "lib/ashfolio/portfolio/calculators/covariance_calculator.ex", "lib/ashfolio/portfolio/calculators/beta_calculator.ex"]
uncommitted: 0 files
commits_ahead: 5

# === TEST ANALYSIS ===
summary:
  total_test_modules: 141
  total_tests: 1911
  average_tests_per_module: 13.6

top_10_test_modules:
  Unknown: 48 tests, 86 assertions (15 describes) | test/ashfolio_web/form_helpers_test.exs
  Unknown: 47 tests, 137 assertions (13 describes) | test/ashfolio/financial_management/retirement_calculator_test.exs
  Unknown: 45 tests, 78 assertions (15 describes) | test/ashfolio/financial/decimal_helpers_test.exs
  Unknown: 44 tests, 66 assertions (14 describes) | test/ashfolio/financial/mathematical_test.exs
  Unknown: 44 tests, 201 assertions (7 describes) | test/ashfolio/financial_management/forecast_calculator_test.exs
  Unknown: 43 tests, 122 assertions (10 describes) | test/ashfolio/portfolio/calculators/risk_metrics_calculator_test.exs
  Unknown: 38 tests, 79 assertions (8 describes) | test/ashfolio/financial/formatters_test.exs
  Unknown: 37 tests, 63 assertions (9 describes) | test/ashfolio/data_helpers_test.exs
  Unknown: 35 tests, 81 assertions (3 describes) | test/ashfolio/portfolio/account_test.exs
  Unknown: 30 tests, 37 assertions (8 describes) | test/ashfolio/error_handler_test.exs

# === TEST GAPS ===
missing_tests:
lib/ashfolio_web/live/example_live.ex ❌
lib/ashfolio_web/components/chart_data.ex ❌
lib/ashfolio_web/components/chart_geometry.ex ❌
lib/ashfolio_web/components/core_components.ex ❌
lib/ashfolio_web/components/holdings_table.ex ❌
orphaned_tests:
test/ashfolio/financial/formatters_chart_test.exs ⚠️
test/ashfolio/financial_management/category_migration_test.exs ⚠️
test/ashfolio/financial_management/forecast_calculator_aer_test.exs ⚠️

# === MODULE ANALYSIS ===
summary:
  total_modules: 148 (140 lib, 8 test)
  total_functions: 2154 (2077 lib, 77 test)
  public/private: 843 public, 1311 private
  average_functions_per_module: 14.6
  complex_modules: 17 (>30 functions)
      empty_modules: 18 (potential parsing issues)

top_20_modules:
  Unknown: 64 functions (1 public, 63 private) | lib/ashfolio_web/components/forecast_chart.ex
  Unknown: 59 functions (32 public, 27 private) | lib/ashfolio/data_helpers.ex
  Unknown: 57 functions (13 public, 44 private) | lib/ashfolio_web/live/financial_goal_live/index.ex
  Unknown: 55 functions (13 public, 42 private) | lib/ashfolio_web/live/dashboard_live.ex
  Unknown: 53 functions (19 public, 34 private) | lib/ashfolio_web/live/transaction_live/index.ex
  Unknown: 51 functions (33 public, 18 private) | lib/ashfolio_web/components/core_components.ex
  Unknown: 49 functions (41 public, 8 private) | lib/ashfolio/financial/formatters.ex
  Unknown: 46 functions (44 public, 2 private) | lib/ashfolio_web/form_helpers.ex
  Unknown: 43 functions (7 public, 36 private) | lib/ashfolio/financial_management/forecast_calculator.ex
  Unknown: 41 functions (5 public, 36 private) | lib/ashfolio/financial_management/contribution_analyzer.ex
  Unknown: 38 functions (1 public, 37 private) | lib/ashfolio_web/components/transaction_group.ex
  Unknown: 38 functions (13 public, 25 private) | lib/ashfolio_web/live/financial_planning_live/forecast.ex
  Unknown: 36 functions (6 public, 30 private) | lib/ashfolio_web/live/expense_live/analytics.ex
  Unknown: 35 functions (16 public, 19 private) | lib/ashfolio_web/live/advanced_analytics_live/index.ex
  Unknown: 33 functions (10 public, 23 private) | lib/ashfolio_web/live/expense_live/index.ex
  Unknown: 32 functions (14 public, 18 private) | lib/ashfolio/financial_management/retirement_calculator.ex
  Unknown: 32 functions (1 public, 31 private) | lib/ashfolio_web/components/transaction_stats.ex
  Unknown: 30 functions (4 public, 26 private) | lib/ashfolio/financial_management/symbol_search.ex
  Unknown: 30 functions (4 public, 26 private) | lib/ashfolio/tax_planning/capital_gains_calculator.ex
  Unknown: 30 functions (15 public, 15 private) | lib/ashfolio_web/live/account_live/index.ex

# === CODE QUALITY ===
credo_analysis: Text parsing summary
credo_issues: 0 


dialyzer_analysis: skipped for performance ⚡

quality_score: 100/100 (0 total issues)

# === PATTERNS ===
error_handling: "Standard put_flash error handling"
currency_format: "Basic decimal formatting"
test_setup: "ExUnit setup blocks (141 total)"

# === INTEGRATION OPPORTUNITIES ===
Add PubSub Subscriptions:
  desc: Add missing PubSub subscriptions: accounts, transactions, net_worth, expenses, goals, prices, forecasts
  priority: medium
  subscribe: lib/ashfolio_web/live/example_live.ex:14

Use Popular Components:
  desc: Consider using frequently used components: modal, flash, simple_form, button, input, input, input, input, input, label
  priority: low
  component:
