# Code GPS v3.1-final | 3 LiveViews | 27 Components

# === ROUTES ===
/: DashboardLive ✅
/accounts: AccountLive ✅
/accounts/new: AccountLive ✅
/accounts/:id: AccountLive ✅
/accounts/:id/edit: AccountLive ✅
/transactions: TransactionLive ✅
/categories: CategoryLive ✅
/categories/new: CategoryLive ✅
/categories/:id/edit: CategoryLive ✅
/expenses: ExpenseLive ✅
/expenses/new: ExpenseLive ✅
/expenses/:id/edit: ExpenseLive ✅
/expenses/import: ExpenseLive ✅
/expenses/analytics: ExpenseLive ✅
/net_worth: NetWorthLive ✅
/goals: FinancialGoalLive ✅
/goals/new: FinancialGoalLive ✅
/goals/:id/edit: FinancialGoalLive ✅
/forecast: ForecastLive ✅
/retirement: RetirementLive ✅
/advanced_analytics: AdvancedAnalyticsLive ✅

# === LIVE VIEWS ===
Dashboard:
  file: lib/ashfolio_web/live/dashboard_live.ex
  mount: 19 | render: 150
  events: ["refresh_prices", "sort", "create_snapshot"]
  subscriptions: [accounts, transactions, net_worth|...5 ]
  missing: []
Example:
  file: lib/ashfolio_web/live/example_live.ex
  mount: 14 | render: 42
  events: ["simulate_error", "simulate_success", "clear_flash"]
  subscriptions: []
  missing: [expenses, net_worth, accounts|...4 ]
Forecast.Index:
  file: lib/ashfolio_web/live/forecast_live.ex
  mount: 23 | render: 269
  events: [update_form, calculate_projection, calculate_scenarios|...5 ]
  subscriptions: ["accounts", "transactions"]
  missing: ["expenses", "net_worth"]


# === KEY COMPONENTS ===
flash: lib/ashfolio_web/components/core_components.ex:111 (7x)
simple_form: lib/ashfolio_web/components/core_components.ex:205 (7x)
button: lib/ashfolio_web/components/core_components.ex:232 (110x)
input: lib/ashfolio_web/components/core_components.ex:295 (45x)
input: lib/ashfolio_web/components/core_components.ex:306 (45x)
input: lib/ashfolio_web/components/core_components.ex:332 (45x)
input: lib/ashfolio_web/components/core_components.ex:351 (45x)
input: lib/ashfolio_web/components/core_components.ex:371 (45x)

# === DEPENDENCIES ===
ash: ❌ (1198)
contex: ❌ (126)
decimal: ❌ (1645)
mox: ❌ (1)

# === FRESHNESS ===
recent: ["config/code_gps_rules.exs", "lib/mix/tasks/code_gps.ex", "test/mix/tasks/code_gps_test.exs", "test/test_helper.exs", "lib/ashfolio/context.ex"]
uncommitted: 14 files
commits_ahead: 5

# === TEST GAPS ===
missing_tests:
lib/ashfolio_web/live/example_live.ex ❌
lib/ashfolio_web/components/core_components.ex ❌
lib/ashfolio_web/components/layouts.ex ❌
lib/ashfolio_web/components/top_bar.ex ❌
lib/ashfolio_web/components/transaction_group.ex ❌
orphaned_tests:
test/ashfolio/financial/formatters_backwards_compatibility_test.exs ⚠️
test/ashfolio/financial_management/category_migration_test.exs ⚠️
test/ashfolio/financial_management/forecast_calculator_aer_test.exs ⚠️

# === CODE QUALITY ===
credo_analysis: 2072 mods/funs, 226 files (2.9s)
credo_issues: 10 refactoring opportunities
  lib/ashfolio/financial/formatters.ex:180 readability: There should be a final \n at the end of each file.
  lib/ashfolio/financial/formatters.ex:4 readability: There should be no trailing white-space at the end of a line.
  lib/ashfolio/financial/formatters.ex:7 readability: There should be no trailing white-space at the end of a line.
  lib/ashfolio/financial/formatters.ex:24 readability: There should be no trailing white-space at the end of a line.
  lib/ashfolio/financial/formatters.ex:31 readability: There should be no trailing white-space at the end of a line.

dialyzer_analysis: skipped for performance ⚡

quality_score: 85/100 (10 total issues)


# === PATTERNS ===
error_handling: "Ashfolio.ErrorHandler.handle_error/2"
currency_format: "FormatHelpers.format_currency"
test_setup: "require Ash.Query; Ash-based test setup"

# === INTEGRATION OPPORTUNITIES ===
# (none)
