# Code GPS v2.0 | 3 LiveViews | 21 Components

# === ROUTES ===
/: DashboardLive ✅
/accounts: AccountLive ✅
/accounts/new: AccountLive ✅
/accounts/:id: AccountLive ✅
/accounts/:id/edit: AccountLive ✅
/transactions: TransactionLive ✅
/categories: CategoryLive ✅
/categories/new: CategoryLive ✅
/categories/:id/edit: CategoryLive ✅
/expenses: ExpenseLive ✅
/expenses/new: ExpenseLive ✅
/expenses/:id/edit: ExpenseLive ✅
/expenses/import: ExpenseLive ✅
/expenses/analytics: ExpenseLive ✅
/net_worth: NetWorthLive ✅
/goals: FinancialGoalLive ✅
/goals/new: FinancialGoalLive ✅
/goals/:id/edit: FinancialGoalLive ✅
/forecast: ForecastLive ✅
/retirement: RetirementLive ✅

# === LIVE VIEWS ===
Dashboard:
  file: lib/ashfolio_web/live/dashboard_live.ex
  mount: 18 | render: 207
  events: ["refresh_prices", "sort", "create_snapshot"]
  subscriptions: [accounts, transactions, net_worth...5]
  missing: []
Example:
  file: lib/ashfolio_web/live/example_live.ex
  mount: 14 | render: 42
  events: ["simulate_error", "simulate_success", "clear_flash"]
  subscriptions: []
  missing: [expenses, net_worth, accounts...4]
Forecast.Index:
  file: lib/ashfolio_web/live/forecast_live.ex
  mount: 23 | render: 269
  events: [update_form, calculate_projection, calculate_scenarios...5]
  subscriptions: ["accounts", "transactions"]
  missing: ["expenses", "net_worth"]


# === KEY COMPONENTS ===
modal: lib/ashfolio_web/components/core_components.ex:46 (2x) | attrs: ["id", "show", "on_cancel"]
flash: lib/ashfolio_web/components/core_components.ex:110 (7x) | attrs: [id, flash, title...5]
flash_group: lib/ashfolio_web/components/core_components.ex:149 (1x) | attrs: ["flash", "id"]
simple_form: lib/ashfolio_web/components/core_components.ex:204 (7x) | attrs: ["for", "as", "rest"]
button: lib/ashfolio_web/components/core_components.ex:231 (20x) | attrs: ["type", "class", "rest"]
input: lib/ashfolio_web/components/core_components.ex:294 (45x) | attrs: [errors, checked, prompt...6]
label: lib/ashfolio_web/components/core_components.ex:397 (3x) | attrs: ["for"]
error: lib/ashfolio_web/components/core_components.ex:410 (9x)

# === DEPENDENCIES ===
ash: ✅ (1123)
contex: ✅ (130)
decimal: ✅ (1455)
mox: ✅ (1)

# === FRESHNESS ===
recent: ["lib/ashfolio/financial_management/financial_goal.ex", "lib/ashfolio_web/components/forecast_chart.ex", "lib/ashfolio_web/components/top_bar.ex", "lib/ashfolio_web/helpers/chart_helpers.ex", "lib/ashfolio_web/live/forecast_live.ex"]
uncommitted: 1 files
commits_ahead: 0

# === TEST GAPS ===
missing_tests:
lib/ashfolio_web/live/example_live.ex ❌
lib/ashfolio_web/components/core_components.ex ❌
lib/ashfolio_web/components/layouts.ex ❌
lib/ashfolio_web/components/top_bar.ex ❌
lib/ashfolio_web/components/transaction_group.ex ❌
orphaned_tests:
test/ashfolio/financial_management/category_migration_test.exs ⚠️
test/ashfolio/financial_management/symbol_search_cache_test.exs ⚠️
test/ashfolio/market_data/price_manager_simple_test.exs ⚠️

# === PATTERNS ===
error_handling: "put_flash/3"
currency_format: "Decimal formatting"
test_setup: "Standard ExUnit setup"

# === INTEGRATION OPPORTUNITIES ===

