defmodule Ashfolio.Repo.Migrations.AddSymbolsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:symbols, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :price_updated_at, :utc_datetime
      add :current_price, :decimal
      add :data_source, :text, null: false
      add :countries, {:array, :text}, default: []
      add :sectors, {:array, :text}, default: []
      add :isin, :text
      add :currency, :text, null: false
      add :asset_class, :text, null: false
      add :name, :text
      add :symbol, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:symbols)
  end
end
