defmodule Ashfolio.Repo.Migrations.CreateTransactionCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transaction_categories, primary_key: false) do
      add :parent_category_id,
          references(:transaction_categories,
            column: :id,
            name: "transaction_categories_parent_category_id_fkey",
            type: :uuid
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "transaction_categories_user_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_system, :boolean, null: false
      add :color, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:transaction_categories, "transaction_categories_user_id_fkey")

    drop constraint(:transaction_categories, "transaction_categories_parent_category_id_fkey")

    drop table(:transaction_categories)
  end
end