defmodule Ashfolio.Repo.Migrations.AddTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transactions, primary_key: false) do
      add :symbol_id,
          references(:symbols, column: :id, name: "transactions_symbol_id_fkey", type: :uuid),
          null: false

      add :account_id,
          references(:accounts, column: :id, name: "transactions_account_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :notes, :text
      add :date, :date, null: false
      add :fee, :decimal, null: false
      add :total_amount, :decimal, null: false
      add :price, :decimal, null: false
      add :quantity, :decimal, null: false
      add :type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:transactions, "transactions_account_id_fkey")

    drop constraint(:transactions, "transactions_symbol_id_fkey")

    drop table(:transactions)
  end
end