defmodule Ashfolio.Repo.Migrations.AddCategoryToTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :category_id,
          references(:transaction_categories,
            column: :id,
            name: "transactions_category_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:transactions) do
      remove :category_id
    end

    drop constraint(:transactions, "transactions_category_id_fkey")
  end
end
