defmodule Ashfolio.Repo.Migrations.AddBalanceUpdatedAtToAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :balance_updated_at, :utc_datetime
    end
  end

  def down do
    alter table(:accounts) do
      remove :balance_updated_at
    end
  end
end