defmodule Ashfolio.Repo.Migrations.AddCashAccountAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :account_type, :text, null: false, default: "investment"
      add :interest_rate, :decimal
      add :minimum_balance, :decimal
    end
  end

  def down do
    alter table(:accounts) do
      remove :minimum_balance
      remove :interest_rate
      remove :account_type
    end
  end
end
