defmodule Ashfolio.Repo.Migrations.AddAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:accounts, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "accounts_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :balance, :decimal, null: false
      add :is_excluded, :boolean, null: false
      add :currency, :text, null: false
      add :platform, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop constraint(:accounts, "accounts_user_id_fkey")

    drop table(:accounts)
  end
end
